version: '3.8'

services:
  rag:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag
    container_name: rag_app
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    #   - ./data:/app/data
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PORT=${PORT}
      - PYTHONPATH=/app:$PYTHONPATH
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3